# constants.py
"""
常量定义模块：定义游戏中使用的常量
"""

# 游戏常量
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
LOGIC_TICK_RATE = 60  # 游戏逻辑更新帧率
LOGIC_DELTA_TIME = 1 / 60  # 游戏逻辑更新的Delta Time
TURN_SIZE = 5    # 每个回合包含的帧数（每隔多少帧同步一次）

# 游戏目录
RESOURCES_DIR = "resources"
IMAGES_DIR = f"{RESOURCES_DIR}/images"
SOUNDS_DIR = f"{RESOURCES_DIR}/sounds"
MAPS_DIR = f"{RESOURCES_DIR}/maps"

# 坦克常量
TANK_SPEED = 5  # 提高坦克速度，从3增加到5
TANK_ROTATION_SPEED = 3
TANK_HEALTH = 100
TANK_AMMO = 999999
TANK_RELOAD_TIME = 300  # 毫秒
TANK_WIDTH = 40
TANK_HEIGHT = 40

# 子弹常量
BULLET_SPEED = 15
BULLET_DAMAGE = 20
BULLET_LIFETIME = 5  # 秒
BULLET_RADIUS = 4

# 障碍物常量
WALL_HEALTH = float('inf')  # 不可破坏
BRICK_HEALTH = 50
OBSTACLE_SIZE = 40  # 默认障碍物尺寸

# 粒子系统常量
PARTICLE_MAX_COUNT = 2000  # 最大粒子数量限制
EXPLOSION_PARTICLE_COUNT = 30
DEBRIS_PARTICLE_COUNT = 20
SPARK_PARTICLE_COUNT = 10

# 颜色
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_GRAY = (128, 128, 128)
COLOR_DARK_GREEN = (0, 100, 0)
COLOR_BROWN = (165, 42, 42)
COLOR_ORANGE = (255, 165, 0)
COLOR_PURPLE = (128, 0, 128)
COLOR_PINK = (255, 192, 203)
COLOR_LIGHT_BLUE = (173, 216, 230)
COLOR_DARK_RED = (139, 0, 0)

# 方向常量
DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3

# 地图常量
MAP_WIDTH = 20  # 地图宽度（以格子数计）
MAP_HEIGHT = 15  # 地图高度（以格子数计）
GRID_SIZE = 40   # 每个格子的大小（像素）

# 游戏事件类型
EVENT_HIT = 1
EVENT_DESTROY = 2
EVENT_GAME_START = 3
EVENT_GAME_END = 4

# 游戏状态
STATE_MENU = 0
STATE_LOADING = 1  # 新增 Loading 状态
STATE_PLAYING = 2  # 由于新增了 LOADING 状态，所以 PLAYING 状态的值变为 2
STATE_PAUSED = 3   # 后续状态值也相应调整
STATE_GAME_OVER = 4

# 游戏模式
MODE_SINGLE_PLAYER = 0
MODE_TWO_PLAYER = 1
MODE_NETWORK = 2

# UI常量
UI_BUTTON_WIDTH = 200
UI_BUTTON_HEIGHT = 50
UI_BUTTON_PADDING = 20
UI_FONT_SIZE = 36
UI_FONT_COLOR = COLOR_WHITE
UI_BUTTON_COLOR = (80, 80, 80)
UI_BUTTON_HOVER_COLOR = (100, 100, 100)
UI_BUTTON_TEXT_COLOR = COLOR_WHITE

# 音效音量
SOUND_VOLUME = 0.5
MUSIC_VOLUME = 0.3

# 网络相关常量
DEFAULT_SERVER_PORT = 8766
DEFAULT_SERVER_HOST = "localhost"
CONNECTION_TIMEOUT = 5000  # 连接超时（毫秒）
RECONNECT_INTERVAL = 1000  # 重连间隔（毫秒）
MIN_PLAYERS = 2  # 最小所需玩家数
MAX_PLAYERS = 4  # 最大支持玩家数

# 网络游戏状态常量
GAME_STATE_WAITING = "waiting"
GAME_STATE_READY = "ready"
GAME_STATE_LOADING = "loading"  # 新增加载状态
GAME_STATE_PLAYING = "playing"
GAME_STATE_PAUSED = "paused"
GAME_STATE_ENDED = "ended"

# 网络调试配置
NETWORK_DEBUG_MODE = True  # 网络调试模式